name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checjout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: PASSO 01
        run: echo "Construir a imagem do app"
      - name: PASSO 02
        run: echo "Publicar a imagem do app no Docker hub"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: PASSO 01
        run: echo "Deploy do app"
